### ISSUE TITLE
Right and left blocks do not appear for v2.5.3

### ISSUE THREAD

**Issue by CaPaCuL** [DPWSMedia/xbtit#37]
Right and left blocks do not appear even when they are active for v2.5.3
![tracker-right-left-blocks-do-not-appear](https://cloud.githubusercontent.com/assets/9300900/20059818/b4a829b4-a500-11e6-811b-70341ada498b.jpg)
 (XBTIT-2-DEV.zip).
Site URL: http://tracker.cevreciler.net

**Comment by Gh0st4unt3r** [comment]
@CaPaCuL  
We have now added the side blocks back again, we hope that you find them ok to work with and any problems please feel free to let us know,
